### PR TITLE
Quiz

### PR DESCRIPTION
**Pull request by zoeames**

### CODE REVIEW

**Comment by tkylesh** [comment]
@zoeames @ncgonz :+1: :-1:

**Comment by zoeames** [comment]
You are SO close.  2 problems:
1.  you have 62 jshint errors
2.  i am seeing "undefined"  show up in the banner instead of my player name when i win

**Comment by zoeames** [comment]
quiz works.  but you still have some grunt errors.  fix those before class tomorrow so you can join the group project

**Comment by tkylesh** [comment]
Will do.  I'll try to get them fixed at work today.

**Comment by tkylesh** [comment]
@zoeames I've fixed the syntax errors.  I don't know how to fix the Robo is not defined and playerOne and playerTwo not defined. I've been staring at it for two weeks and I have no clue.  It seems to me if they weren't defined the program wouldn't work yet it does.

**Comment by zoeames** [comment]
the easiest way to fix the "Robo is not defined" is to put Robo in your gruntfile in the predef

**Comment by zoeames** [comment]
playerOne and playerTwo are a different issue.  i believe the problem is that you are trying to add click events inside an iife augmenter.  seems like you should be doing the click events in app.js where you have playerOne and playerTwo defined.  You will have to modify your code slightly to do this because battle is not defined in app.js

**Comment by zoeames** [comment]
I will be at NSS around 5pm today if you want to sit and work through it before class

**Comment by tkylesh** [comment]
@zoeames Thanks.  I can be there at 5.  I'll keep working on it until then.

**Comment by tkylesh** [comment]
@zoeames It may be fixed.  I'm not getting anymore jshint errors and everything seems to be working.

**Comment by zoeames** [comment]
yep now that looks great! 👍

**Comment by tkylesh** [comment]
thanks for the help! @zoeames

**Pull request merged**
